# Generated by Django 5.2.7 on 2025-11-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(help_text="Укажите дату оплаты", verbose_name="Дата оплаты"),
        ),
    ]
