# Generated by Django 5.2.5 on 2025-08-08 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название курса", max_length=100, verbose_name="Название курса"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью",
                        null=True,
                        upload_to="lms/previews",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Введите описание", null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Укажите урок", max_length=150, verbose_name="Урок")),
                ("description", models.TextField(help_text="Введите описание", verbose_name="Описание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью",
                        null=True,
                        upload_to="lms/previews",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True, help_text="Укажите ссылку на видео", null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите курс",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
