# Generated by Django 5.2.7 on 2025-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время последнего уведомления"),
        ),
    ]
